[project]
name = "mcp_planning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.10.2",
    "ruff>=0.12.2",
]
