[project]
name = "mcp_planning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "fastmcp>=2.10.2",
    "ipykernel>=6.29.5",
    "python-dotenv>=1.1.1",
    "ruff>=0.12.2",
]
